# Generated by Django 6.1.1 on 2026-09-07 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_number', models.PositiveIntegerField()),
                ('visit_type', models.CharField(choices=[('Screening', 'Screening'), ('Baseline', 'Baseline'), ('Follow Up', 'Follow Up'), ('Unscheduled', 'Unscheduled'), ('End of Study', 'End of Study')], max_length=50)),
                ('scheduled_date', models.DateField()),
                ('actual_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Scheduled', 'Scheduled'), ('Completed', 'Completed'), ('Missed', 'Missed'), ('Cancelled', 'Cancelled')], default='Scheduled', max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='participants.participant')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('participant', 'visit_number'), name='unique_participant_visit_number')],
            },
        ),
    ]
