# Generated by Django 6.1.1 on 2026-09-07 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0002_studydocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='study',
            name='phase',
            field=models.CharField(choices=[('Phase 1', 'Phase 1'), ('Phase 2', 'Phase 2'), ('Phase 3', 'Phase 3'), ('Phase 4', 'Phase 4')], max_length=50),
        ),
        migrations.AlterField(
            model_name='study',
            name='status',
            field=models.CharField(choices=[('Planning', 'Planning'), ('Recruiting', 'Recruiting'), ('Active', 'Active'), ('Completed', 'Completed'), ('Suspended', 'Suspended'), ('Terminated', 'Terminated')], max_length=50),
        ),
        migrations.AlterField(
            model_name='studydocument',
            name='category',
            field=models.CharField(choices=[('Protocol', 'Protocol'), ('Investigator Brochure', 'Investigator Brochure'), ('Informed Consent Form', 'Informed Consent Form'), ('Site Document', 'Site Document'), ('Training Document', 'Training Document'), ('Other', 'Other')], max_length=100),
        ),
    ]
